#数据库连接配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.94.166.191:3306/tensquare_base?useSSL=false&characterEncoding=utf-8
      username: root
      password: 15139923838li

#redis配置
  redis:
    port: 6379
    host: 121.199.3.37
    database: 0

#服务端口号
server:
  port: 9005

#mybatisPlus配置
mybatis-plus:
  mapper-locations: classPath:com.tensquare.qa.dao/*.xml
  type-aliases-package: com.qw.com.tensquare.qa.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

