server:
  port: 9004 # 服务访问端口号
spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.166.191:3306/tensquare_article?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 15139923838li
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  type-aliases-package: com.tensquare.article.pojo
  global-config:
    id-type: 1 # 0数据库id自增 1用户输入id
    db-column-underline: false # 实体字段是否转换为下划线格式
    refresh-mapper: true # 自动刷新mapper.xml
  configuration:
    map-underscore-to-camel-case: true # 将带有下划线的表字段映射为驼峰格式的实体类属性。
    cache-enabled: true # 配置缓存的全局开关
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml